### PR TITLE
added a change in readme for installing in python3.5 and python3.6

### PR DESCRIPTION
**Pull request by nightwarrior-xxx**

### CODE REVIEW

**Comment by vaibhavsingh97** [comment]
@nightwarrior-xxx Thanks for the PR 💯 
IMO, it's not needed as `pip` handles the installation for both python 2.x and python 3.x. If your system has the default `python 2.x` it will install the package automatically.
Ref: https://pip.pypa.io/en/stable/installing/

Also, before opening PR, It would be great if you open Issue first, as this PR holds no value as it's not referencing to the issue it fixes. Thanks

**Comment by nightwarrior-xxx** [comment]
Please check the README.md once again 
And I was getting problem while installing using pip ,he was showing an error that he could not install using this version so I have to use "pip3 " for installing

**Comment by vaibhavsingh97** [comment]
@nightwarrior-xxx Can you please open issue with relevant screenshots and information

**Comment by nightwarrior-xxx** [comment]
Error while installing thorugh "python3 setup.py install"
screenshot from 2018-07-13 00-41-18

**Comment by vaibhavsingh97** [comment]
@nightwarrior-xxx Yeah, It's because of `config.py` is missing. Please check https://github.com/vaibhavsingh97/random-word#development for more details.
Also, I fixed pip issue and thanks for reporting it :)

**Comment by vaibhavsingh97** [comment]
closing since there is no update. Feel free to open new PR

**Pull request closed without merging**
